name: docs

on:
  push:
    branches: [ feat/docs ]

jobs:
  java-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Create custom Maven Settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          output_file: custom_maven_settings.xml
          servers: '[{ "id": "github-packages-compas", "username": "OWNER", "password": "${{ secrets.GITHUB_TOKEN }}" }]'

      - name: Build docs with Maven
        run: mvn -s custom_maven_settings.xml  javadoc:javadoc

      - name: Commit javadoc changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global commit.gpgsign true
            git config --global user.name 'Config CI Robot'
            git config --global user.email 'config-ci-robot@users.noreply.github.com'
            git checkout -b fix/docs
            git add -A
            git commit -S -m "Automated javadocs updates."
            git push fix/docs
          fi
#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v3.8.2
#        with:
#          title: "Automated API website updates."
#          commit-message: "Automated API documentation website updates."