# SPDX-FileCopyrightText: 2022 RTE FRANCE
#
# SPDX-License-Identifier: Apache-2.0

name: REUSE Compliance Check

on:
  push:
    branches:
      - '!feat/docs'
      - '!fixes/docs'
      -  '!feat/117_Documentation_SCD_Generation_Process'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
